name: Almanix
favicon: null
layout_spectrum: 0.87706
typography_spectrum: 0.25725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edece2'
    - '#000000'
    - '#989791'
    - '#725429'
    - '#393836'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
