name: Almanix Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55753
title: 'Arquitetura de Projetos | Direção Criativa |  Identidades Visuais '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-54793210-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edece2'
    - '#000000'
    - '#989791'
    - '#725429'
    - '#393836'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
